/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <iostream>
/* Header for class com_jouav_jni_TestNative */

#ifndef _Included_com_jouav_jni_TestNative
#define _Included_com_jouav_jni_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jouav_jni_TestNative
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jouav_jni_TestNative_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

void JNICALL Java_com_jouav_jni_TestNative_sayHello(JNIEnv* env, jobject obj)
{
  std::cout << "JNI: Hello world!" << std::endl;
  jclass clazz_TestNative = env->GetObjectClass(obj); //通过传入的 obj 类的对象获取当前类
  jfieldID id_number = env->GetFieldID(clazz_TestNative, "number", "I");  //类实例, 属性名,(sign)数据类型
  jint number = env->GetIntField(obj, id_number); //  通过 ID 获取当前变量
  std::cout << "原数据： " << number << std::endl;
  env->SetIntField(obj, id_number, 100L); // 类实例,变量 ID, 修改的 java 属性值
}

#include "pch.h"